/**
 * TypeScript models for Solar Investigation management
 * These models match the backend Pydantic models for API compatibility
 */

export enum InvestigationStatus {
    PENDING = 'pending',
    RUNNING = 'running',
    COMPLETED = 'completed',
    FAILED = 'failed',
    CANCELLED = 'cancelled'
}

export enum AgentMessageType {
    USER = 'user',
    AGENT = 'agent',
    SYSTEM = 'system',
    THINKING = 'thinking',
    TOOL_CALL = 'tool_call',
    TOOL_RESULT = 'tool_result'
}

export interface AgentMessage {
    id: string;
    investigation_id: string;
    message_type: AgentMessageType;
    content: string;
    metadata?: { [key: string]: any };
    timestamp: string; // ISO string from backend

    // UI State fields
    ui_summary?: Array<{ summary: string, full_content: string, timestamp: string }>; // List of UI summaries for display
    ui_state?: { [key: string]: any }; // UI-specific state data
    show_full_content?: boolean; // Whether to show full content by default
}

export interface InvestigationRequest {
    plant_id: string;
    start_date: string; // ISO date string (YYYY-MM-DD)
    end_date: string; // ISO date string (YYYY-MM-DD)
    additional_notes?: string;
    parent_id?: string; // ID of parent investigation if this is a retry
}

export interface Investigation {
    id: string;
    plant_id: string;
    plant_name?: string; // Will be populated from plant data
    start_date: string; // ISO date string
    end_date: string; // ISO date string
    additional_notes?: string;
    status: InvestigationStatus;
    session_id?: string;
    user_id: string;
    parent_id?: string; // ID of parent investigation if this is a retry
    created_at: string; // ISO string from backend
    updated_at: string; // ISO string from backend
    completed_at?: string;
    result?: { [key: string]: any };
    error_message?: string;
    agent_stats?: { // Rich ADK agent interaction statistics
        total_events: number;
        user_messages: number;
        agent_responses: number;
        thinking_steps: number;
        tool_calls: number;
        tools_used: string[];
        total_agents: string[];
        session_duration?: number;
        last_activity?: string;
        progress_steps: Array<{
            step_number: number;
            step_name: string;
            timestamp: string;
            completed: boolean;
        }>;
    };

    // UI-specific fields from ADK session state
    ui_summary?: Array<{ summary: string, full_content: string, timestamp: string }>; // List of UI summaries generated by after_agent_callback
}

export interface InvestigationResponse {
    investigation: Investigation;
    message: string;
}

export interface InvestigationListResponse {
    investigations: Investigation[];
    total: number;
    page: number;
    size: number;
}

export interface ChatHistoryResponse {
    investigation_id: string;
    messages: AgentMessage[];
    total_messages: number;
}

export interface DecisionRequest {
    decision: string;
    decision_type?: string;
    additional_data?: { [key: string]: any };
}

export interface DecisionResponse {
    investigation_id: string;
    decision_accepted: boolean;
    message: string;
    next_steps?: string[];
}

export interface MessageRequest {
    content: string;
    message_type?: AgentMessageType;
}

export interface HealthResponse {
    status: string;
    timestamp: string;
    service: string;
}

// Legacy interface for backward compatibility with existing dashboard component
export interface LegacyInvestigation {
    id: string;
    title: string;
    status: 'running' | 'complete' | 'failed';
    agentChat: LegacyAgentMessage[];
    findings?: string;
    createdAt: Date;
    projectId?: string;
}

export interface LegacyAgentMessage {
    agentName: string;
    message: string;
    timestamp: Date;
}
